name: deteksi_pembusukan_daging
description: Aplikasi monitoring deteksi risiko pembusukan daging sapi segar menggunakan sensor DHT22 dan AI berbasis Arduino Uno

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  go_router: ^16.2.4
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.0
  syncfusion_flutter_gauges: ^31.1.21
  syncfusion_flutter_charts: ^31.1.21
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
